# Generated by Django 3.2.2 on 2021-05-11 09:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_pg', '0004_auto_20210511_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
